name: Samba server
description: Expose Home Assistant folders with SMB/CIFS
url: https://github.com/ElVit/hassio-addons/tree/main/samba
version: 1.3.4
stage: stable
slug: samba
codenotary: notary@home-assistant.io
startup: services
init: false
boot: auto
hassio_role: default
hassio_api: true
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - all_addon_configs:rw
  - homeassistant_config:rw
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  custom_config: false
  logins:
    - username: dummyUser
      password: null
schema:
  custom_config: bool
  logins:
    - username: str
      password: password
