name: Traefik
description: Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy.
url: https://github.com/ElVit/hassio-addons/tree/main/traefik
version: 1.3.6
stage: stable
slug: traefik
codenotary: notary@home-assistant.io
startup: system
init: false
boot: auto
hassio_role: default
hassio_api: true
auth_api: true
ingress: true
ingress_entry: dashboard/
panel_icon: mdi:earth-arrow-right
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
  - ssl:rw
options:
  custom_config: false
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  letsencrypt:
    enabled: false
    resolvers: []
  env_vars: []
schema:
  custom_config: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  env_vars:
    - str
