---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base-nodejs:0.2.5
  amd64: ghcr.io/hassio-addons/base-nodejs:0.2.5
  armv7: ghcr.io/hassio-addons/base-nodejs:0.2.5
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  BW_CLI_VERSION: 2024.12.0
