---
# https://github.com/hassio-addons/addon-base
build_from:
  aarch64: ghcr.io/hassio-addons/base:18.0.3
  amd64: ghcr.io/hassio-addons/base:18.0.3
  armhf: ghcr.io/hassio-addons/base:18.0.3
  armv7: ghcr.io/hassio-addons/base:18.0.3
  i386: ghcr.io/hassio-addons/base:18.0.3
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
