# https://github.com/home-assistant/builder

name: 'Build and test Bitwarden secrets for Home Assistant'

env:
  ADD_ON_DIRECTORY: bitwarden-secrets

on:
  push:
    paths:
      - 'bitwarden-secrets/**'
    branches:
      - master
  pull_request:
    paths:
      - 'bitwarden-secrets/**'

jobs:
  build:
    name: Test build Bitwarden secrets for Home Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --armv7 --amd64 --aarch64 \
            --target /data/${ADD_ON_DIRECTORY} \
            --docker-hub ghcr.io/elvit \
            --image ${ADD_ON_DIRECTORY}-add-on
            
