name: 'Build and test Bitwarden secrets for Home Assistant'

env:
  ADDON_DIRECTORY: bitwarden-secrets

on:
  push:
    paths:
      - 'bitwarden-secrets/**'
    branches:
      - main
  pull_request:
    paths:
      - 'bitwarden-secrets/**'
  workflow_dispatch:

jobs:
  build:
    name: Test build Bitwarden secrets for Home Assistant
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      # https://github.com/home-assistant/builder
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --armv7 --amd64 --aarch64 \
            --target /data/${ADDON_DIRECTORY} \
            --docker-hub ghcr.io/elvit \
            --image ${ADDON_DIRECTORY}-addon
